{-|
Module      : HOI4.CountryNames
Description : The name the wiki calls each country by

A hand-kept table, from the wiki's editors, of what to call each country when
the choice is ours. The game often asks only that a country be named somehow
-- a flag template, the heading over a focus tree, a name command in drawn
text -- without saying which of a country's several names to use, and these
are the names the wiki reaches for then. Text that asks for one particular
form -- an adjective, the name apart from any ideology -- is the game being
specific, and is still answered from the game's own localization.

One entry per tag in @common/country_tags/00_countries.txt@. The names are
the editors' own choices, not always a string the game holds: some shorten a
game name (Two Sicilies), some pick one form over another (Taiwan rather than
Formosa), and some name a country the game never does (Sakha).
-}
module HOI4.CountryNames (
        casualName
    ) where

import Data.HashMap.Strict (HashMap)
import qualified Data.HashMap.Strict as HM
import Data.Text (Text)

-- | The name the wiki knows a country by, for the tags it has settled one for.
casualName :: Text -> Maybe Text
casualName tag = HM.lookup tag casualNames

casualNames :: HashMap Text Text
casualNames = HM.fromList
    [ ("ABK", "Abkhazia")
    , ("ADU", "Al-Andalus")
    , ("AFA", "Sultanate of Aussa")
    , ("AFG", "Afghanistan")
    , ("ALB", "Albania")
    , ("ALG", "Algeria")
    , ("ALT", "Altai")
    , ("ANG", "Angola")
    , ("ANU", "Ainu Republic")
    , ("AOI", "Italian East Africa")
    , ("ARG", "Argentina")
    , ("ARM", "Armenia")
    , ("AST", "Australia")
    , ("ASY", "Assyria")
    , ("ATJ", "Aceh")
    , ("AUS", "Austria")
    , ("AZR", "Azerbaijan")
    , ("BAH", "Bahamas")
    , ("BAN", "Bangladesh")
    , ("BAR", "Barotseland")
    , ("BAS", "British Antilles")
    , ("BAY", "Bavaria")
    , ("BEG", "Benishangul-Gumuz Nation")
    , ("BEL", "Belgium")
    , ("BHR", "Bahrain")
    , ("BHU", "Bhutan")
    , ("BIA", "Biafra")
    , ("BLC", "Balochistan")
    , ("BLI", "Bali")
    , ("BLR", "Belarus")
    , ("BLZ", "Belize")
    , ("BOL", "Bolivia")
    , ("BOS", "Bosnia-Herzegovina")
    , ("BOT", "Botswana")
    , ("BOU", "Bougainville")
    , ("BRA", "Brazil")
    , ("BRD", "Burundi")
    , ("BRI", "Brittany")
    , ("BRM", "British Burma")
    , ("BRN", "Brunei")
    , ("BSK", "Bashkortostan")
    , ("BUK", "Bukhara")
    , ("BUL", "Bulgaria")
    , ("BYA", "Buryatia")
    , ("CAM", "Cambodia")
    , ("CAN", "Dominion of Canada")
    , ("CAR", "Central African Republic")
    , ("CAT", "Catalonia")
    , ("CAY", "Guiana")
    , ("CBV", "Cabo Verde")
    , ("CHA", "Chad")
    , ("CHI", "China")
    , ("CHL", "Chile")
    , ("CHM", "Champa Republic")
    , ("CHR", "Charrúa Nation")
    , ("CHU", "Chuvashia")
    , ("CIN", "Chechnya-Ingushetia")
    , ("CIP", "Central Indian Princely States")
    , ("CKK", "Chukotka")
    , ("CMR", "Cameroon")
    , ("COG", "Congolese State")
    , ("COL", "Colombia")
    , ("COR", "Corsica")
    , ("COS", "Costa Rica")
    , ("CPS", "Champasak")
    , ("CRC", "Netherlands Antilles")
    , ("CRI", "Crimea")
    , ("CRO", "Croatia")
    , ("CSA", "Confederacy of American States")
    , ("CUB", "Cuba")
    , ("CYP", "Cyprus")
    , ("CZE", "Czechoslovakia")
    , ("DAG", "Dagestan")
    , ("DAH", "Dahomey")
    , ("DDR", "German Democratic Republic")
    , ("DEN", "Denmark")
    , ("DIP", "Indian Partisans")
    , ("DJI", "Djibouti")
    , ("DNZ", "Free City of Danzig")
    , ("DOM", "Dominican Republic")
    , ("DON", "Don Cossack Host")
    , ("ECU", "Ecuador")
    , ("EGY", "Egypt")
    , ("ELS", "El Salvador")
    , ("ENG", "United Kingdom")
    , ("EQG", "Equatorial Guinea")
    , ("ERI", "Eritrea")
    , ("EST", "Estonia")
    , ("ETH", "Ethiopia")
    , ("EVE", "Evenkia")
    , ("EZO", "Ezo Republic")
    , ("FER", "Far Eastern Republic")
    , ("FIJ", "Melanesian Federation")
    , ("FIN", "Finland")
    , ("FOR", "Taiwan")
    , ("FRA", "France")
    , ("FSA", "Federation of South Arabia")
    , ("FSM", "Micronesia")
    , ("GAB", "Gabon")
    , ("GAL", "Galicia and Lodomeria")
    , ("GAM", "The Gambia")
    , ("GAR", "Guaraní Nation")
    , ("GBA", "Gambela")
    , ("GDC", "Guangdong Clique")
    , ("GDL", "Guadeloupe")
    , ("GEN", "Generalgouvernement")
    , ("GEO", "Georgia")
    , ("GER", "German Reich")
    , ("GHA", "Ghana")
    , ("GLC", "Galicia")
    , ("GNA", "Guinea")
    , ("GNB", "Guinea-Bissau")
    , ("GOW", "Gowa")
    , ("GRE", "Greece")
    , ("GRN", "Greenland")
    , ("GSM", "Gansu Ma")
    , ("GUA", "Guatemala")
    , ("GUM", "Mariana Federation")
    , ("GXC", "Guangxi Clique")
    , ("GYA", "Guyana")
    , ("HAI", "Haiti")
    , ("HAN", "Westphalia")
    , ("HAR", "Harar")
    , ("HAW", "Hawai'i")
    , ("HBC", "Hebei-Chahar")
    , ("HES", "Hesse")
    , ("HOL", "Netherlands")
    , ("HON", "Honduras")
    , ("HRZ", "Herzegovina")
    , ("HUN", "Hungary")
    , ("HYD", "Hyderabad")
    , ("IAS", "Isthmo-Amerindian State")
    , ("ICE", "Iceland")
    , ("IMO", "Imamate of Oman")
    , ("INC", "Inca Empire")
    , ("INS", "Dutch East Indies")
    , ("INU", "United Inuit States")
    , ("IRE", "Ireland")
    , ("IRQ", "Iraq")
    , ("ISR", "Israel")
    , ("ITA", "Italy")
    , ("ITZ", "Itza Nation")
    , ("IVO", "Côte d'Ivoire")
    , ("JAM", "Jamaica")
    , ("JAN", "Jan Mayen")
    , ("JAP", "Japan")
    , ("JOR", "Emirate of Transjordan")
    , ("KAL", "Kalmykia")
    , ("KAR", "Karelia")
    , ("KAS", "Kashmir")
    , ("KAT", "Katanga")
    , ("KAZ", "Kazakhstan")
    , ("KBK", "Kabardino-Balkaria")
    , ("KEN", "Kenya")
    , ("KHA", "Khakassia")
    , ("KHI", "Khiva")
    , ("KHL", "Khalistan")
    , ("KHM", "Khotan Ma")
    , ("KKP", "Karakalpakstan")
    , ("KLT", "Kalat")
    , ("KOL", "Kolhapur and Deccan States")
    , ("KOM", "Komi")
    , ("KOR", "Korea")
    , ("KOS", "Kosovo")
    , ("KSH", "Kashubia")
    , ("KUB", "Kuban National Republic")
    , ("KUM", "Kumul Khanate")
    , ("KUR", "Kurdistan")
    , ("KUW", "Sheikhdom of Kuwait")
    , ("KYR", "Kyrgyzstan")
    , ("LAO", "Laos")
    , ("LAT", "Latvia")
    , ("LBA", "Libya")
    , ("LBV", "Lombardy-Venetia")
    , ("LEB", "Lebanese Republic")
    , ("LIB", "Liberia")
    , ("LIT", "Lithuania")
    , ("LUX", "Luxembourg")
    , ("MAC", "Macedonia")
    , ("MAD", "Madagascar")
    , ("MAL", "British Malaya")
    , ("MAN", "Qing China")
    , ("MAY", "Maya State")
    , ("MEK", "Mecklenburg")
    , ("MEL", "Mari El")
    , ("MEN", "Mengjiang")
    , ("MEX", "Mexico")
    , ("MIS", "Mosquito Kingdom")
    , ("MLD", "Maldives")
    , ("MLI", "Mali")
    , ("MLT", "Malta")
    , ("MLW", "Malawi")
    , ("MNT", "Montenegro")
    , ("MOL", "Moldova")
    , ("MON", "Mongolia")
    , ("MOR", "Morocco")
    , ("MPU", "Manipur")
    , ("MRT", "Mauritania")
    , ("MYS", "Mysore")
    , ("MZB", "Mozambique")
    , ("NAH", "Nahua Nation")
    , ("NAV", "Basque Country")
    , ("NEN", "Nenetsia")
    , ("NEP", "Nepal")
    , ("NGA", "Nigeria")
    , ("NGR", "Niger")
    , ("NIC", "Nicaragua")
    , ("NIR", "Northern Ireland")
    , ("NMB", "Namibia")
    , ("NOA", "North Ossetia-Alania")
    , ("NOR", "Norway")
    , ("NWF", "North-Western Frontier Provinces")
    , ("NXM", "Ningxia Ma")
    , ("NZL", "New Zealand")
    , ("OCC", "Occitania")
    , ("OKN", "Ryukyu Kingdom")
    , ("OMA", "Oman")
    , ("ORO", "Oromia")
    , ("OVO", "Ostyakia-Vogulia")
    , ("PAK", "Pakistan")
    , ("PAL", "Mandatory Palestine")
    , ("PAN", "Panama")
    , ("PAP", "Papal States")
    , ("PAR", "Paraguay")
    , ("PER", "Iran")
    , ("PHI", "Philippines")
    , ("PLU", "Palau")
    , ("PNG", "Papua New Guinea")
    , ("POK", "Pontianak")
    , ("POL", "Poland")
    , ("POR", "Portugal")
    , ("PRC", "Chinese Soviet Republic")
    , ("PRE", "Prussia")
    , ("PRU", "Peru")
    , ("PSH", "Pashtunistan")
    , ("PSR", "Second Philippine Republic")
    , ("PUE", "Puerto Rico")
    , ("QAT", "Qatar")
    , ("QEM", "Qemant State")
    , ("QUE", "Québec")
    , ("RAA", "Reichskommissariat Australasien")
    , ("RAJ", "British Raj")
    , ("RAN", "Reichskommissariat Anden")
    , ("RAP", "Rapa Nui")
    , ("RAR", "Reichskommissariat Arabien")
    , ("RAS", "Madras Princely States")
    , ("RCG", "Congo-Brazzaville")
    , ("RCO", "Reichskommissariat Kolumbus")
    , ("RGB", "Reichskommissariat Großbritannien")
    , ("RHD", "Reichskommissariat Hindustan")
    , ("RHI", "Rhenish Republic")
    , ("RIF", "The Rif")
    , ("RIG", "Rio Grande")
    , ("RJP", "Rajputana")
    , ("RKA", "Reichskommissariat Mittelafrika")
    , ("RKB", "Reichskommissariat Belgien-Nordfrankreich")
    , ("RKC", "Reichskommissariat Balkan")
    , ("RKG", "Reichskommissariat Norwegen")
    , ("RKH", "Protektorat Böhmen-Mähren")
    , ("RKI", "Reichskommissariat Iberien")
    , ("RKK", "Reichskommissariat Kaukasien")
    , ("RKL", "Reichskommissariat Ural")
    , ("RKM", "Reichskommissariat Moskowien")
    , ("RKN", "Reichskommissariat Niederlande")
    , ("RKO", "Reichskommissariat Ostland")
    , ("RKT", "Reichskommissariat Turkestan")
    , ("RKU", "Reichskommissariat Ukraine")
    , ("RKV", "Reichskommissariat Klein-Venedig")
    , ("RNA", "Reichskommissariat Nordafrika")
    , ("RNG", "Reorganized National Government of the Republic of China")
    , ("ROA", "Reichskommissariat Ostasien")
    , ("ROM", "Romania")
    , ("RUS", "Reichskommissariat Nordamerika")
    , ("RUT", "Carpatho-Ukraine")
    , ("RWA", "Rwanda")
    , ("SAB", "Sabah")
    , ("SAF", "South Africa")
    , ("SAM", "Samoa")
    , ("SAR", "Sarawak")
    , ("SAU", "Saudi Arabia")
    , ("SAX", "Saxony")
    , ("SCO", "Scotland")
    , ("SDL", "Sudetenland")
    , ("SEN", "Senegal")
    , ("SER", "Serbia")
    , ("SHL", "Schleswig-Holstein")
    , ("SHX", "Shanxi")
    , ("SIA", "Siam")
    , ("SIC", "Sichuan Clique")
    , ("SID", "Sidamo")
    , ("SIE", "Sierra Leone")
    , ("SIK", "Sinkiang")
    , ("SIL", "Silesia")
    , ("SIN", "Sindh")
    , ("SKK", "Sikkim")
    , ("SLO", "Slovakia")
    , ("SLV", "Slovenia")
    , ("SMI", "Sápmi")
    , ("SND", "Shandong Clique")
    , ("SNG", "Singapore")
    , ("SOK", "Sokoto")
    , ("SOL", "Solomon Islands")
    , ("SOM", "Somalia")
    , ("SOV", "Soviet Union")
    , ("SPM", "Sardinia-Piedmont")
    , ("SPR", "Spain")
    , ("SRL", "Sri Lanka")
    , ("SSI", "Siak")
    , ("SUD", "Sudan")
    , ("SUR", "Suriname")
    , ("SWE", "Sweden")
    , ("SWI", "Switzerland")
    , ("SYR", "Republic of Syria")
    , ("TAH", "Tahiti")
    , ("TAJ", "Tajikistan")
    , ("TAN", "Tannu Tuva")
    , ("TAT", "Tatarstan")
    , ("TAY", "Taymyria")
    , ("THU", "Thuringia")
    , ("TIB", "Tibet")
    , ("TIG", "Tigray")
    , ("TML", "Timor-Leste")
    , ("TMS", "Turkmenistan")
    , ("TNE", "Ternate")
    , ("TOG", "Togo")
    , ("TOS", "Tuscany")
    , ("TRA", "Transylvania")
    , ("TRI", "Trinidad and Tobago")
    , ("TTS", "Two Sicilies")
    , ("TUN", "Tunisia")
    , ("TUR", "Turkey")
    , ("TZN", "Tanzania")
    , ("UAE", "Trucial States")
    , ("UBD", "United Baltic Duchy")
    , ("UDM", "Udmurtia")
    , ("UGA", "Uganda")
    , ("UKR", "Ukraine")
    , ("URG", "Uruguay")
    , ("USA", "United States")
    , ("USB", "Unaligned States of America")
    , ("UZB", "Uzbekistan")
    , ("VAN", "Vanuatu")
    , ("VEN", "Venezuela")
    , ("VGE", "Volga Germany")
    , ("VIN", "Vietnam")
    , ("VLA", "Vladivostok")
    , ("VOL", "Upper Volta")
    , ("WES", "Sahrawi Arab Democratic Republic")
    , ("WGR", "Federal Republic of Germany")
    , ("WIS", "Western Indian States")
    , ("WLA", "Y Wladychfa Gymreig")
    , ("WLS", "Wales")
    , ("WPG", "West Papua")
    , ("WUR", "Baden-Württemberg")
    , ("XIC", "Northeastern Army")
    , ("XSM", "Qinghai Ma")
    , ("YAK", "Sakha")
    , ("YAM", "Yamalia")
    , ("YEM", "Yemen")
    , ("YUC", "Yucatán")
    , ("YUG", "Yugoslavia")
    , ("YUN", "Yunnan")
    , ("ZAM", "Zambia")
    , ("ZIM", "Zimbabwe")
    ]
